"""Write the LaTeX macros Figure 1's TikZ diagram reads.

Figure 1 is a worked example, not a schematic: every actor, every clock reading
and both discarded events belong to one real pull request. The TikZ source must
therefore never carry a literal number, or the diagram and the artifact would
drift apart the first time the worked example is regenerated. This script reads
``outputs/worked_example/`` and emits ``paper/manuscript/fig1_values.tex``, a
file of ``\\newcommand`` definitions that the diagram uses for every word and
every coordinate that depends on the data.

Two constants are easy to confuse and are kept apart deliberately:

* the burst *window* is a design parameter of the study (``burst_minutes``),
  not an observed duration;
* the landmark hour is when merges *start being counted*, not when this pull
  request merged. This one merged after it, and the diagram places both on the
  same axis so the reader can see that.

Run: ``uv run --quiet python scripts/figures/generate_figure1_macros.py``
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EXAMPLE = ROOT / "outputs" / "worked_example"
TARGET = ROOT / "paper" / "manuscript" / "fig1_values.tex"

# The diagram draws one badge per discarded event and needs a short tag for
# each. The tag is keyed on the rule identifier in the artifact, so a renamed
# or removed rule fails loudly here instead of silently mislabelling a badge.
DISCARD_TAGS = {
    "same-batch exclusion": "same review batch",
    "burst exclusion": "inside the burst window",
}

LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def escape(text: str) -> str:
    return "".join(LATEX_ESCAPES.get(character, character) for character in text)


def read_timeline() -> list[dict[str, str]]:
    with (EXAMPLE / "timeline.csv").open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError("The worked example timeline is empty")
    return sorted(rows, key=lambda row: int(row["order"]))


def trim(value: float) -> str:
    """Render a float without a trailing ``.0`` so labels read as prose."""
    text = f"{value:.1f}"
    return text[:-2] if text.endswith(".0") else text


def main() -> None:
    summary = json.loads((EXAMPLE / "summary.json").read_text(encoding="utf-8"))
    timeline = read_timeline()

    by_rule = {row["rule"]: row for row in timeline}
    for required in ("trigger", "addressed edge", "landmark", "outcome"):
        if required not in by_rule:
            raise ValueError(f"The worked example no longer exercises {required!r}")

    # The figure's claim that the chain leaves the products rests on these two
    # fields, so they are checked rather than assumed.
    if by_rule["trigger"]["actor_role"] != "reviewing product":
        raise ValueError("The trigger is no longer written by the reviewing product")
    if by_rule["addressed edge"]["actor_role"] != "a person":
        role = by_rule["addressed edge"]["actor_role"]
        raise ValueError(
            "Figure 1 says the qualifying reply comes from a person; the worked "
            f"example now records that actor as {role!r}"
        )

    discards = [row for row in timeline if row["rule"] in DISCARD_TAGS]
    if len(discards) != 2:
        raise ValueError(
            "Figure 1 draws exactly two discarded events; the worked example now "
            f"has {len(discards)}"
        )

    repository = summary["repository"].rstrip("/").split("/repos/")[-1]
    author = summary["author_product"].replace("_", " ")
    reviewer = summary["reviewing_product"].replace("_", " ")
    burst_minutes = float(summary["burst_minutes"])
    landmark_hours = float(summary["landmark_hours"])
    reply_hours = float(by_rule["addressed edge"]["minutes_after_trigger"]) / 60.0
    merge_hours = float(by_rule["outcome"]["minutes_after_trigger"]) / 60.0
    merge_days = merge_hours / 24.0

    if merge_hours <= landmark_hours:
        raise ValueError(
            "Figure 1 shows the merge landing after the landmark; the worked "
            f"example now merges at {merge_hours:.1f} h, on or before hour "
            f"{landmark_hours:.0f}"
        )

    # The time axis is linear in hours and must hold the merge with room for
    # its arrow head, so its span is derived from the data, not hard-coded.
    axis_max_hours = max(merge_hours, landmark_hours) * 1.04

    lines = [
        "% Generated by scripts/figures/generate_figure1_macros.py -- do not edit.",
        "% Source: outputs/worked_example/{summary.json,timeline.csv}",
        "%",
        "% Every word and every coordinate in fig1_diagram.tex that depends on the",
        "% worked example comes from this file, so the diagram cannot drift away",
        "% from the pull request it claims to describe.",
        "",
        rf"\newcommand{{\FigOneRepo}}{{\texttt{{{escape(repository)}}}}}",
        rf"\newcommand{{\FigOneAuthor}}{{{escape(author)}}}",
        rf"\newcommand{{\FigOneReviewer}}{{{escape(reviewer)}}}",
        rf"\newcommand{{\FigOnePerson}}{{{escape(by_rule['addressed edge']['actor_role'])}}}",
        "",
        "% Clock readings, as the figure prints them.",
        rf"\newcommand{{\FigOneReplyHours}}{{{trim(reply_hours)}}}",
        rf"\newcommand{{\FigOneMergeDays}}{{{trim(merge_days)}}}",
        rf"\newcommand{{\FigOneBurstMinutes}}{{{trim(burst_minutes)}}}",
        rf"\newcommand{{\FigOneLandmarkHours}}{{{trim(landmark_hours)}}}",
        "",
        "% The same readings as bare numbers, for placing marks on the axis.",
        rf"\newcommand{{\FigOneReplyAt}}{{{reply_hours:.4f}}}",
        rf"\newcommand{{\FigOneMergeAt}}{{{merge_hours:.4f}}}",
        rf"\newcommand{{\FigOneLandmarkAt}}{{{landmark_hours:.4f}}}",
        rf"\newcommand{{\FigOneBurstEndAt}}{{{burst_minutes / 60.0:.4f}}}",
        rf"\newcommand{{\FigOneAxisMax}}{{{axis_max_hours:.4f}}}",
        "",
        "% The two events a rule discards, each with the rule that caught it.",
    ]

    for index, row in enumerate(discards, start=1):
        name = ("One", "Two")[index - 1]
        lines.extend(
            [
                rf"\newcommand{{\FigOneDrop{name}Actor}}{{{escape(row['actor_role'])}}}",
                rf"\newcommand{{\FigOneDrop{name}Event}}{{{escape(row['event'])}}}",
                rf"\newcommand{{\FigOneDrop{name}Rule}}{{{escape(DISCARD_TAGS[row['rule']])}}}",
            ]
        )

    lines.append("")
    TARGET.write_text("\n".join(lines), encoding="utf-8")

    print(
        json.dumps(
            {
                "wrote": str(TARGET.relative_to(ROOT)),
                "repository": repository,
                "author_product": author,
                "reviewing_product": reviewer,
                "reply_hours": round(reply_hours, 2),
                "merge_days": round(merge_days, 2),
                "burst_window_minutes": burst_minutes,
                "landmark_hours": landmark_hours,
                "discarded": [row["rule"] for row in discards],
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
